map: "warehouse"
world: "warehouse"
rviz_file: "sim_env.rviz"

robots_config:
  - robot1_type: "turtlebot3_waffle"
    robot1_global_planner: "a_star"
    robot1_local_planner: "lqr"
    robot1_x_pos: "0.0"
    robot1_y_pos: "0.0"
    robot1_z_pos: "0.0"
    robot1_yaw: "0.0"

# * global planner
#   * graph_planner
#     * a_star
#     * jps
#     * gbfs
#     * dijkstra
#     * d_star
#     * lpa_star
#     * voronoi
#     * d_star_lite
#     * theta_star
#     * lazy_theta_star
#     * hybrid_a_star
#
#   * sample_planner
#     * rrt
#     * rrt_star
#     * rrt_connect
#     * informed_rrt
#     * quick_informed_rrt
#
#   * evolutionary_planner
#     * aco
#     * pso
#     * ga
#   * lazy_planner
#
# * local planner
#   * dwa
#   * pid
#   * apf
#   * rpp
#   * lqr
#   * static

plugins:
  # pedestrians: "pedestrian_config.yaml"
  # obstacles: "obstacles_config.yaml"
  map_layers: "map_layers_config.yaml"
