global_costmap:
  global_frame: map
  robot_base_frame: base_footprint

  update_frequency: 1.0
  publish_frequency: 1.0
  transform_tolerance: 0.5

  static_map: true

  inflation_radius: 1.0

  # plugins:
  #   - {name: static_map,       type: "costmap_2d::StaticLayer"}
  # #   - {name: voxel_layer,        type: "costmap_2d::VoxelLayer"}
  #   - {name: obstacle_layer,        type: "costmap_2d::ObstacleLayer"}
  #   - {name: voronoi_layer,        type: "costmap_2d::VoronoiLayer"}     
  #   - {name: inflation_layer,        type: "costmap_2d::InflationLayer"}