PIDPlanner:
  # next point distance/turning angle
  p_window: 0.2
  o_window: 1.0

  # goal reached tolerance
  p_precision: 0.2
  o_precision: 0.5

  # linear velocity
  max_v: 0.5
  min_v: 0.0
  max_v_inc: 0.5

  # angular velocity
  max_w: 1.57
  min_w: 0.0
  max_w_inc: 1.57

  # pid controller params
  k_v_p: 1.00
  k_v_i: 0.10
  k_v_d: 0.10

  k_w_p: 1.00
  k_w_i: 0.10
  k_w_d: 0.10

  k_theta: 0.3
