GraphPlanner:
  # offset of transform from world(x,y) to grid map(x,y)
  convert_offset: 0.0
  # error tolerance
  default_tolerance: 0.0
  # whether outline the map or not
  outline_map: true
  # obstacle inflation factor
  obstacle_factor: 0.5
  # whether publish expand zone or not
  expand_zone: true
  # whether to store Voronoi map or not
  voronoi_map: false
